Tienda_compu/Models/ProductoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tienda_compu.DAL;

namespace Tienda_compu.Models
{
    public class ProductoesController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Productoes
        public ActionResult Index()
        {
            var producto = db.Producto.Include(p => p.Categoria);
            return View(producto.ToList());
        }

        // GET: Productoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Productoes/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(db.Categoria, "Id", "Nombre");
            return View();
        }

        // POST: Productoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Marca,Ram,Almacenamiento,Peso,Precio,Color,ImageUrl,Teclado,TipoPantalla,CategoriaId")] Producto producto, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    string pic = System.IO.Path.GetFileName(upload.FileName);
                    string path = System.IO.Path.Combine(
                                           Server.MapPath("~/Images"), pic);

                    upload.SaveAs(path);



                    var photo = new Image
                    {
                        ImageName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Photo

                    };
                    producto.Images = new List<Image>();
                    producto.Images.Add(photo);
                }
                db.Producto.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(db.Categoria, "Id", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // GET: Productoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categoria, "Id", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // POST: Productoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Marca,Ram,Almacenamiento,Peso,Precio,Color,Cantidad,Teclado,TipoPantalla,CategoriaId")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categoria, "Id", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // GET: Productoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Producto.Find(id);
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tienda_compu/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda_compu.DAL;
namespace Tienda_compu.Models
{
    public class ShoppingCart : Controller
    {
        private StoreContext storeDB = new StoreContext();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        public void AddToCart(Producto Producto)
        {
            // Get the matching cart and album instances
            var cartItem = storeDB.Carritos.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ProductoId == Producto.Id);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Carrito
                {
                    ProductoId = Producto.Id,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                storeDB.Carritos.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count++;
            }
            // Save changes
            storeDB.SaveChanges();
        }
        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = storeDB.Carritos.Single(
                cart => cart.CartId == ShoppingCartId
                && cart.RecordId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    storeDB.Carritos.Remove(cartItem);
                }
                // Save changes
                storeDB.SaveChanges();
            }
            return itemCount;
        }
        public void EmptyCart()
        {
            var cartItems = storeDB.Carritos.Where(
                cart => cart.CartId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                storeDB.Carritos.Remove(cartItem);
            }
            // Save changes
            storeDB.SaveChanges();
        }
        public List<Carrito> GetCartItems()
        {
            return storeDB.Carritos.Where(
                cart => cart.CartId == ShoppingCartId).ToList();
        }
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in storeDB.Carritos
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }
        public decimal GetTotal()
        {
            // Multiply album price by count of that album to get 
            // the current price for each of those albums in the cart
            // sum all album price totals to get the cart total
            decimal? total = (from cartItems in storeDB.Carritos
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Producto.Precio).Sum();

            return total ?? decimal.Zero;
        }
        public int CreateOrder(Orden order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrdenDetalle
                {
                    ProductoId = item.ProductoId,
                    OrdenId = order.OrdenId,
                    PrecioUnitario = item.Producto.Precio,
                    Cantidad = item.Count
                };
                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Producto.Precio);

                storeDB.OrdenDetalles.Add(orderDetail);

            }
            // Set the order's total to the orderTotal count
            order.Total = orderTotal;

            // Save the order
            storeDB.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return order.OrdenId;
        }
        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = storeDB.Carritos.Where(
                c => c.CartId == ShoppingCartId);

            foreach (Carrito item in shoppingCart)
            {
                item.CartId = userName;
            }
            storeDB.SaveChanges();
        }
    }
}

Tienda_compu/Models/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda_compu.DAL;
using Tienda_compu.ViewModels;

namespace Tienda_compu.Models
{
    public class ShoppingCartController : Controller
    {
        private ProductoesController productControl = new ProductoesController();
        private StoreContext storeDB = new StoreContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            
                var addedAlbum = storeDB.Producto
            
                .Single(producto => producto.Id == id);

           
            
                // Add it to the shopping cart
                var cart = ShoppingCart.GetCart(this.HttpContext);

                cart.AddToCart(addedAlbum);
                

              
                
                // Go back to the main store page for more shopping
                return RedirectToAction("Index");
            
           
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carritos
                .Single(item => item.RecordId == id).Producto.Nombre;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

      
    }
}

Tienda_compu/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tienda_compu.Models;

namespace Tienda_compu.ViewModels
{
    public class ShoppingCartViewModel
    {
        public int Id { get; set; }
        public List<Carrito> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

Tienda_compu/Views/ShoppingCart/Index.cshtml
@model Tienda_compu.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}
<script src="<%: Url.Content( '~/Scripts/jquery.unobtrusive-ajax.min.js') %>" type="text/javascript"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"
        type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", {"id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });
    });
</script>
<h3>
    <em>Revisa</em> tu carrito:
</h3>


<input type="button" class="btn btn-info" value="Checkout" onclick="location.href='@Url.Action("AddressAndPayment", "Checkout")'" />
<div id="update-message">
</div>
<!--Roxana-->
<div class="container">
    <div class="row">
        <div class="col-xs-7">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">
                        <div class="row">
                            <div class="col-xs-6">
                                <h5><span class="glyphicon glyphicon-shopping-cart"></span> Carrito de Compra</h5>
                            </div>
                            <div class="col-xs-6">
                                <button type="button" class="btn btn-primary btn-sm btn-block" onclick="location.href='@Url.Action("Index", "Productoes")'">
                                    <span class="glyphicon glyphicon-share-alt"></span> Sigue Comprando
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <table>
                            <tr>
                                <th>
                                    <div class="col-xs-1">
                                        <div class="col-xs-1 text-left">
                                            <h4><strong>Producto</strong></h4>
                                        </div>
                                    </div>
                                </th>
                                <th>
                                    <div class="col-xs-2">
                                        <div class="col-xs-2 text-left">
                                            <h4><strong>Precio Unitario</strong></h4>
                                        </div>
                                    </div>
                                </th>
                                <th>
                                    <div class="col-xs-2">
                                        <div class="col-xs-3 text-left">
                                            <h4><strong>Cantidad</strong></h4>
                                        </div>
                                    </div>
                                </th>
                                <th></th>
                            </tr>
                            @foreach (var item in
Model.CartItems)
                            {
                                <tr id="row-@item.RecordId">
                                    <td>
                                        @Html.ActionLink(item.Producto.Nombre,
"Details", "Store", new { id = item.ProductoId }, null)
                                    </td>
                                    <td>
                                        @item.Producto.Precio
                                    </td>
                                    <td id="item-count-@item.RecordId">
                                        @item.Count
                                    </td>
                                    <td>
                                        <div >
                                            <button  class="RemoveLink" data-id="@item.RecordId">
                                                Remove from cart
                                                
                                            </button>
                                        </div>
                                       
                                    </td>
                                </tr>
                            }
                            <tr>
                                <td>
                                    Total
                                </td>
                                <td></td>
                                <td></td>
                                <td id="cart-total">
                                    @Model.CartTotal
                                </td>
                               
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>